name: Run Actions Before Merge

on:
  pull_request_review:
    types: [ submitted ]

  workflow_dispatch:

jobs:
  debug:
  runs-on: ubuntu-latest
  steps:
    - name: 'head.ref'
      run: echo ${{ github.event.pull_request.head.ref }}
    - name: 'base.ref'
      run: echo ${{ github.event.pull_request.base.ref }}

  pull_request_review_if_main:
    name: 
    if: github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success...

  pull_request_review_if_main_and_approved:
    name: 
    if: github.event.pull_request.head.ref == 'main' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success...