name: Run Actions Before Merge

on:
  pull_request_review:
    types: [ submitted ]

  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    outputs:
      truthy-value: ${{ steps.output-truth.outputs.truthy-value }}
    steps:
      - name: 'head.ref'
        run: 'echo ${{ github.event.pull_request.head.ref }}'
      - name: 'base.ref'
        run: 'echo ${{ github.event.pull_request.base.ref }}'
      - name: 'github.event_name'
        run: 'echo ${{ github.event_name}}'
      - name: 'for conditional testing'
        id: output-truth
        run: 'echo "truthy-value=true" >> $GITHUB_OUTPUT'


  pull_request_review_if_main_plus_additional_checks:
    name: Pass if head.ref is main OR fail AND output from another job
    needs: [ debug ]
    if: ${{ (github.event.pull_request.base.ref == 'main' || github.event_name == 'this-wont-work') && needs.debug.outputs.truthy-value == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success...

  pull_request_review_if_main_and_approved:
    name: Pass is head ref is main and approved
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success...

  pull_request_review_if_approved_or_dispatch_and_not_draft:
    name: Pass is head ref is main and approved
    if: ${{ (github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch') && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Success...

