name: Debug Runner

on:
  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        description: Image tag
        required: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: 'pwd'
        run: 'pwd'
      - name: 'github.ref'
        run: echo "${{ github.ref }}"
      - name: 'github.sha'
        run: echo "${{ github.sha }}"
      - name: 'github.ref_name'
        run: echo "${{ github.ref_name }}"
      - name: 'Interp input string'
        run: echo "UAT-${{ inputs.image_tag }}"