name: Debug Runner

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    outputs:
      truthy-value: ${{ steps.output-truth.outputs.truthy-value }}
    steps:
      - name: 'pwd'
        run: 'pwd'