name: Debug Runner

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: string
        description: Image tag
        required: true
      COMMITISH:
        type: string
        description: Image tag
        required: true

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: 'pwd'
        run: 'pwd'
      - name: 'github.ref'
        run: echo "${{ github.ref }}"
      - name: 'github.sha'
        run: echo "${{ github.sha }}"
      - name: 'github.ref_name'
        run: echo "${{ github.ref_name }}"
      - name: 'Interp input string'
        run: echo "UAT-${{ inputs.image_tag }}"

  tag-test:
    name: tag-test
    runs-on: ubuntu-latest
    steps:
      - name: Verify tag format
        if: contains(github.event.inputs.ENVIRONMENTS, 'prod')
        run: |
          TAG_NAME=${{ github.event.inputs.COMMITISH || github.ref }}
          if [[ "${TAG_NAME}" == refs/tags/* || "${TAG_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "This is a release"
          else
            echo "ERROR: only tags with format vX.Y.Z are allowed for production deployments" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - name: Set image tag
        id: set-image-tag
        run: |
          TAG_NAME=${{ github.event.inputs.COMMITISH || github.sha }}
          if [[ "${TAG_NAME}" == refs/tags/* || "${TAG_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            IMAGE_TAG="PROD-${GITHUB_SHA}"
          else
            # Use the commit hash for non-release deployments when triggered by a workflow dispatch with branch
            IMAGE_TAG="UAT-${GITHUB_SHA}"
          fi
          echo "$IMAGE_TAG"