name: Debug Runner

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: 'pwd'
        run: 'pwd'
      - name: 'github.ref'
        run: echo "${{ github.ref }}"
      - name: 'github.sha'
        run: echo "${{ github.sha }}"
      - name: 'github.ref_name'
        run: echo "${{ github.ref_name }}"