name: Format Testing

on:
    workflow_dispatch:
      inputs:
        RUN_OUTPUT:
          description: 'Should run output?'
          type: boolean

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Output Something
        if: inputs.RUN_OUTPUT
        id: output
        run: |
          echo "docker_image_uri=AWESOME" >> $GITHUB_OUTPUT

      - name: Check Format
        run: 'echo "DOCKER IMAGE: $DOCKER_IMAGE"'
        env:
          DOCKER_IMAGE: ${{ steps.output.outputs.docker_image_uri || format('clientapi:{0}', 'DEFAULT') }}