name: Format Testing

on:
    workflow_dispatch:
      inputs:
        ENVIRONMENTS:
          description: 'Comma separated list'
          type: string
        UAT_CLIENTS:
          description: 'Comma separated list'
          type: string

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Output Something
        id: output
        run: |
          echo "docker_image_uri=AWESOME" >> $GITHUB_OUTPUT

      - name: Check Format
        run: 'echo "DOCKER IMAGE: $DOCKER_IMAGE"'
        env:
          DOCKER_IMAGE: ${{ steps.output.outputs.docker_image_uri || format('clientapi:{0}', 'DEFAULT') }}