name: Matrix Testing

on:
  workflow_dispatch:
    inputs:
      CLIENTS:
        type: string
        description: 'Comma separated list of client names'
jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build Matrix
        id: build-matrix
        # run: |
        #   CLIENT_NAMES_RAW=${{ github.event.inputs.CLIENTS }}
          
          
        #   # echo "deploy-matrix=$CLIENT_NAMES" | tee -a $GITHUB_OUTPUT

        #   set -eux
        #   # CLIENT_NAMES=$(echo "$CLIENT_NAMES_RAW" | jq -R 'split(",")')
        #   CLIENT_NAMES=$(echo "$CLIENT_NAMES_RAW" | jq -c '. | map(split(",")[0]) | unique'
        #   echo "deploy-matrix=$CLIENT_NAMES" >> $GITHUB_OUTPUT
        run: |
          echo '${{ github.event.inputs.CLIENTS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' | xargs -I '{}' echo "{}" >> "$GITHUB_OUTPUT"
          echo $(cat $GITHUB_OUTPUT)
  deploy:
    runs-on: ubuntu-lates
    needs: [ parse-inputs ]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.parse-inputs.outputs.deploy-matrix) }}
    steps:
      - name: Reloading the Matrix
        run: |
          echo "RELOADING: ${{ matrix.environment }}"