name: Matrix Testing

on:
  workflow_dispatch:
    inputs:
      CLIENTS:
        type: string
        description: 'Comma separated list of client names'

jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build Matrix
        uses: actions/github-script@v7
        id: build-matrix
        with:
          # result-encoding: json
          script: |
            const clients = process.env.CLIENTS;
            // goal: "[\"uat\",\"dev\",\"prod\"]"
            console.log(`RAW: ${clients}`);

            const newClients = `[${clients.split(',').map(c => '\"' + c + '\"')}]`

            console.log(`PARSED: ${newClients}`);
            core.setOutput('deploy-matrix', newClients);
        env:
          CLIENTS: ${{ github.event.inputs.CLIENTS }}

  deploy:
    runs-on: ubuntu-lates
    needs: [ parse-inputs ]
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.parse-inputs.outputs.deploy-matrix) }}
        # environment: ${{ fromJson(github.event.inputs.CLIENTS) }}
    steps:
      - name: Reloading the Matrix
        run: |
          echo "RELOADING: ${{ matrix.environment }}"