name: Matrix Testing

on:
  workflow_dispatch:
    inputs:
      CLIENTS:
        type: string
        description: 'Comma separated list of client names'

jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build Matrix
        uses: actions/github-script@v7
        id: build-matrix
        with:
          # result-encoding: json
          script: |
            const clients = process.env.CLIENTS;
            console.log(`CLIENTS(typeof clients): ${JSON.stringify(clients)}`);

            const newClients = JSON.stringify(clients.split(','));
            console.log(`NEW: ${newClients}`);
            core.setOutput('newClients', build-matrix);
        env:
          CLIENTS: ${{ github.event.inputs.CLIENTS }}

  deploy:
    runs-on: ubuntu-lates
    needs: [ parse-inputs ]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.parse-inputs.outputs.deploy-matrix) }}
    steps:
      - name: Reloading the Matrix
        run: |
          echo "RELOADING: ${{ matrix.environment }}"