name: Matrix Testing

on:
  workflow_dispatch:
    inputs:
      CLIENTS:
        type: string
        description: 'Comma separated list of client names'
      ENVIRONMENTS:
        type: string
        description: 'Comma separated list of environment names'

jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.build-matrix.outputs.deploy-matrix }}
    continue-on-error: true
    steps:
      - name: Build Matrix
        uses: actions/github-script@v7
        id: build-matrix
        with:
          # result-encoding: json
          script: |
            const clients = process.env.CLIENTS;
            console.log(`RAW: ${clients}`);

            // Parse into cdk names
            const cdkClients = clients
              .replace("uat", "UAT")
              .replace("uatpr", "UAT-PR")
              .replace("prod", "Prod")

            // goal: ["uat","dev","prod"]
            const newClients = `[${cdkClients.split(',').map(c => '\"' + c + '\"')}]`

            console.log(`PARSED: ${newClients}`);
            core.setOutput('deploy-matrix', newClients);
        env:
          CLIENTS: ${{ github.event.inputs.CLIENTS }}

      - name: DEBUG PARSED
        run: |
          DEBUG='${{ fromJson(steps.build-matrix.outputs.deploy-matrix) }}'
          echo "PARSED: $DEBUG"

  parse-inputs-double:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.build-matrix.outputs.deploy-matrix }}
      last-matrix-value: ${{ steps.build-matrix.outputs.last-matrix-value }}
    continue-on-error: true
    steps:
      - name: Build Matrix
        uses: actions/github-script@v7
        id: build-matrix
        with:
          # result-encoding: json
          script: |
            const clients = process.env.CLIENTS;
            console.log(`RAW: ${clients}`);

            // Parse into cdk commands
            const clientCommands = clients
              .replace("uat", "uat/*")
              .replace("prod", "prod/*")
              .split(',')

            const envCommands = isArray(environments)
              ? environments.split(',').map(env => `uat/clientapi-${env}`)
              
            const commands = clientCommands.concat(envCommands)
            const commands = `[${commands.map(c => '\"' + c + '\"')}]`

            // goal: ["uat","dev","prod"]
            const newClients = `[${cdkClients.split(',').map(c => '\"' + c + '\"')}]`

            console.log(`PARSED: ${newClients}`);
            core.setOutput('deploy-matrix', newClients);
        env:
          CLIENTS: ${{ github.event.inputs.CLIENTS }}

      - name: DEBUG PARSED
        run: |
          DEBUG='${{ fromJson(steps.build-matrix.outputs.deploy-matrix) }}'
          echo "PARSED: $DEBUG"

  deploy:
    runs-on: ubuntu-latest
    needs: [ parse-inputs ]
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.parse-inputs.outputs.deploy-matrix) }}
    steps:
      - name: Reloading the Matrix
        id: reload
        run: |
          echo "RELOADING: ${{ matrix.environment }}"

      - name: Output
        id: output
        run: |
          echo "${{ matrix.environment }}=${{ steps.reload.outcome }}" >> output.txt

      - name: 

  output:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    steps:
      - name: Output the Matrix
        run: |
          echo "${{ needs.deploy.outputs }}"

      - name: Output results (always shows success)
        run: |
          echo "${{ needs.deploy.result }}"

  deploy-input-will-fail:
    runs-on: ubuntu-latest
    needs: [ parse-inputs ]
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(github.event.inputs.CLIENTS) }}
    steps:
      - name: Reloading the Matrix
        run: |
          echo "RELOADING: ${{ matrix.environment }}"