name: Required Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      api1-changed: ${{ steps.changed-files.outputs.api1_any_changed}}
      api2-changed: ${{ steps.changed-files.outputs.api2_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Checking Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
              api1:
              - api1/**
              api2:
              - api2/**

  api1-test:
    name: Test API 1
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.api1-changed
    steps:
      - name: Test
        run: echo "TESTING"

  api2-test:
    name: Test API 
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: echo "TESTING"

  ok-to-merge:
    name: OK To Merge
    runs-on: ubuntu-latest
    needs: [ setup, api1-test, api2-test ]
    if: always()
    steps:
      - name: Determine if required checks passed
        uses: actions/github-script@v7
        with:
          script: |
            // Determine what should pass
            const setupOutputs = ${{ needs.setup.outputs }}
            console.log(`OUTPUTS: ${setupOutputs}`)

            // Determine if those things passed, ignore the others
            


      # - run: |
      #     # Determine what should pass

      #     # Determine if those things passed, ignore the others
      #     # --> exit 0 if ok to merge
      #     # --> exit 1 if not

      #     # exit 0 + Skipped jobs are "success"
      #     api1-tests-passed="${{ needs.api1-test.result.success }}"
