name: Required Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      # api1-changed: ${{ steps.changed-files.outputs.api1_any_changed}}
      # api2-changed: ${{ steps.changed-files.outputs.api2_any_changed }}
      api1-changed: true
      api2-changed: false
    steps:
      - uses: actions/checkout@v4
      - name: Checking Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
              api1:
              - api1/**
              api2:
              - api2/**

  api1-test:
    name: Test API 1
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.api1-changed
    steps:
      - name: Test
        run: echo "TESTING"

  api2-test:
    name: Test API 
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: echo "TESTING"

  ok-to-merge:
    name: OK To Merge
    runs-on: ubuntu-latest
    needs: [ setup, api1-test, api2-test ]
    if: always()
    steps:
      - name: Determine if required checks passed
        uses: actions/github-script@v7
        env:
          API1_CHANGED: ${{ needs.setup.outputs.api1-changed }}
          INPUT_API1_CHANGED: ${{ needs.setup.outputs.api1-changed }}
        with:
          script: |
            // Determine what should pass
            const setupOutputs = process.env.SETUP_OUTPUTS
            const setupOutputs2 = process.env.INPUT_SETUP_OUTPUTS
            console.log(`OUTPUTS: ${JSON.stringify(setupOutputs,null,2)}\n`)
            console.log(`OUTPUTS 2: ${JSON.stringify(setupOutputs2,null,2)}`)

            // Determine if those things passed, ignore the others