name: Required Checks

on:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      api1-changed: ${{ steps.changed-files.outputs.api1_any_changed}}
      api2-changed: ${{ steps.changed-files.outputs.api2_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Checking Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
              api1:
              - api1/**
              api2:
              - api2/**

  api1-test:
    name: Test API 1
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "TESTING"

  api2-test:
    name: Test API 
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "TESTING"