name: Use Composite Actions

on:
  workflow_dispatch:

jobs:
  run-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy@main

  run-nested-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/api-tests/api@main