name: Use Composite Actions

on:
  workflow_dispatch:

jobs:
  run-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/actions/deploy

  run-nested-composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/actions/api-tests/api